[package]
name = "rust-compress-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
lz4_flex = "0.11"
rand = "0.8"
lz4 = "1.24"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "compression_benchmark"
harness = false